/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cautruclaptrinhpart5.Bai5;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neo
 */
public class TroiChoiXoSo extends javax.swing.JFrame {

    /**
     * Creates new form TroiChoiXoSo
     */
    public TroiChoiXoSo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtgetLo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtgetDiemLo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtgetDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        txtgetTienDe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDay = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtDB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNhat = new javax.swing.JTextField();
        txtNhi1 = new javax.swing.JTextField();
        txtNhi2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtBa1 = new javax.swing.JTextField();
        txtBa2 = new javax.swing.JTextField();
        txtBa3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTu1 = new javax.swing.JTextField();
        txtBa4 = new javax.swing.JTextField();
        txtBa5 = new javax.swing.JTextField();
        txtBa6 = new javax.swing.JTextField();
        txtTu2 = new javax.swing.JTextField();
        txtTu3 = new javax.swing.JTextField();
        txtTu4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNam1 = new javax.swing.JTextField();
        txtNam2 = new javax.swing.JTextField();
        txtNam3 = new javax.swing.JTextField();
        txtNam4 = new javax.swing.JTextField();
        txtNam5 = new javax.swing.JTextField();
        txtNam6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSau1 = new javax.swing.JTextField();
        txtSau2 = new javax.swing.JTextField();
        txtSau3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBay1 = new javax.swing.JTextField();
        txtBay2 = new javax.swing.JTextField();
        txtBay3 = new javax.swing.JTextField();
        txtBay4 = new javax.swing.JTextField();
        btnViewDate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtGetDate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Đặt cược và Nhận Thưởng"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Đặt Cược và Quay Số"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("XỔ SỐ LÔ TÔ - CHƠI LÀ TRÚNG Ô TÔ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lô: ");

        txtgetLo.setText("10");

        jLabel3.setText("x");

        txtgetDiemLo.setText("200");
        txtgetDiemLo.setHighlighter(null);

        jLabel4.setText("VNĐ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Đề:");

        txtgetDe.setText("07");

        jLabel6.setText(" VNĐ.");

        btnRoll.setText("Quay thưởng");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        txtgetTienDe.setText("100000");

        jLabel7.setText("x");

        txtDay.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtDay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Thời gian mở thưởng:");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cautruclaptrinhpart5/Bai5/image (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtgetLo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtgetDe, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtgetTienDe, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(txtgetDiemLo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel21))
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgetLo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtgetDiemLo))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtgetDe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgetTienDe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kết quả quay thưởng"));

        jLabel8.setText("Đặc biệt:");

        txtDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDB.setForeground(new java.awt.Color(255, 0, 0));
        txtDB.setText(" ");

        jLabel10.setText("Giải Nhất");

        jLabel11.setText("Giải Nhì");

        jLabel12.setText("Giải Ba");

        jLabel13.setText("Giải Tư");

        jLabel14.setText("Giải Năm");

        txtNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNam1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Giải Sáu");

        jLabel16.setText("Giải Bảy");

        txtBay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBay2ActionPerformed(evt);
            }
        });

        btnViewDate.setText("Xem kết quả");
        btnViewDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDateActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", null},
                {"1", null},
                {"2", null},
                {"3", null},
                {"4", null},
                {"5", null},
                {"6", null},
                {"7", null},
                {"8", null},
                {"9", null}
            },
            new String [] {
                "Đầu", "Lô Tô"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        }

        jLabel18.setText("Nhập ngày cần xem :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Tổng tiền thưởng:");

        jLabel20.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBay1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBay2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBay3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBay4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSau1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSau2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSau3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNam1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNam2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNam3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNam4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNam5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNam6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTu1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTu2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtBa4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBa5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBa6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtTu3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTu4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(217, 217, 217)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDB, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(txtNhat)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(txtBa1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(txtNhi1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNhi2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBa2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBa3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewDate, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(366, 366, 366))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBa6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNam1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSau3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGetDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBay2ActionPerformed

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed
        // TODO add your handling code here:
        String strGetLo, strGetDiemLo, strGetDe, strGetTienDe;
        int iLo = 0, iDe = 0, iTienLo = 0, iTienDe = 0;
        strGetLo = txtgetLo.getText();
        strGetDiemLo = txtgetDiemLo.getText();
        strGetDe = txtgetDe.getText();
        strGetTienDe = txtgetTienDe.getText();
        try {
            iLo = Integer.parseInt(strGetLo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập số hợp lệ!");
            txtgetLo.requestFocus();
            return;
        }
        try {
            iDe = Integer.parseInt(strGetDe);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập số hợp lệ!");
            txtgetDiemLo.requestFocus();
            return;
        }
        try {
            iTienLo = Integer.parseInt(strGetDiemLo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập số hợp lệ!");
            txtgetDe.requestFocus();
            return;
        }
        try {
            iTienDe = Integer.parseInt(strGetTienDe);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập số hợp lệ!");
            txtgetTienDe.requestFocus();
        }
        if (iLo < 0 || iLo > 99 || iDe < 0 || iDe > 99) {
            JOptionPane.showMessageDialog(rootPane, "Mời bạn nhập số hợp lệ!");
            txtgetTienDe.requestFocus();
            return;
        }
        String strLo = "" + iLo;
        if (iLo < 10) {
            strLo = "0" + iLo;
        }
        String strDe = "" + iDe;
        if (iDe < 10) {
            strDe = "0" + iDe;
        }
        // Tạo object GiaiThuong()
        GiaiThuong gt = new GiaiThuong();
        // random giai
        Random r = new Random();
        // Random tạo giải và hiển thị
        // Tạo listLo lưu 2 số cuối các giải
        gt.strDB = "" + r.nextInt(100000);
        gt.strDB = check(gt.strDB, 5);
        gt.lstLo.add(gt.strDB.substring(3));
        txtDB.setText(gt.strDB);

        gt.strNhat = "" + r.nextInt(100000);
        gt.strNhat = check(gt.strNhat, 5);
        gt.lstLo.add(gt.strNhat.substring(3));
        txtNhat.setText(gt.strNhat);

        gt.strNhi1 = "" + r.nextInt(100000);
        gt.strNhi1 = check(gt.strNhi1, 5);
        txtNhi1.setText(gt.strNhi1);
        gt.lstLo.add(gt.strNhi1.substring(3));

        gt.strNhi2 = "" + r.nextInt(100000);
        gt.strNhi2 = check(gt.strNhi2, 5);
        txtNhi2.setText(gt.strNhi2);
        gt.lstLo.add(gt.strNhi2.substring(3));
        // giai ba
        gt.strBa = new String[6];
        for (int i = 0, l = gt.strBa.length; i < l; i++) {
            gt.strBa[i] = check("" + r.nextInt(100000), 5);
            gt.lstLo.add(gt.strBa[i].substring(3));
        }
        txtBa1.setText(gt.strBa[0]);
        txtBa2.setText(gt.strBa[1]);
        txtBa3.setText(gt.strBa[2]);
        txtBa4.setText(gt.strBa[3]);
        txtBa5.setText(gt.strBa[4]);
        txtBa6.setText(gt.strBa[5]);
        //giai tu
        gt.strTu = new String[4];
        for (int i = 0, l = gt.strTu.length; i < l; i++) {
            gt.strTu[i] = check("" + r.nextInt(10000), 4);
            gt.lstLo.add(gt.strTu[i].substring(2));
        }
        txtTu1.setText(gt.strTu[0]);
        txtTu2.setText(gt.strTu[1]);
        txtTu3.setText(gt.strTu[2]);
        txtTu4.setText(gt.strTu[3]);
        //giai nam
        gt.strNam = new String[6];
        for (int i = 0, l = gt.strNam.length; i < l; i++) {
            gt.strNam[i] = check("" + r.nextInt(10000), 4);
            gt.lstLo.add(gt.strNam[i].substring(2));
        }
        txtNam1.setText(gt.strNam[0]);
        txtNam2.setText(gt.strNam[1]);
        txtNam3.setText(gt.strNam[2]);
        txtNam4.setText(gt.strNam[3]);
        txtNam5.setText(gt.strNam[4]);
        txtNam6.setText(gt.strNam[5]);
        // giai sau
        gt.strSau = new String[3];
        for (int i = 0, l = gt.strSau.length; i < l; i++) {
            gt.strSau[i] = check("" + r.nextInt(1000), 3);
            gt.lstLo.add(gt.strSau[i].substring(1));
        }
        txtSau1.setText(gt.strSau[0]);
        txtSau2.setText(gt.strSau[1]);
        txtSau3.setText(gt.strSau[2]);
        //giai bay
        gt.strBay = new String[4];
        for (int i = 0, l = gt.strBay.length; i < l; i++) {
            gt.strBay[i] = "" + r.nextInt(100);
            gt.strBay[i] = check(gt.strBay[i], 2);
            gt.lstLo.add(gt.strBay[i]);
        }
        txtBay1.setText(gt.strBay[0]);
        txtBay2.setText(gt.strBay[1]);
        txtBay3.setText(gt.strBay[2]);
        txtBay4.setText(gt.strBay[3]);
        // Tạo list chứa các đầu loto
        for (String string : gt.lstLo) {
            char dauLoto = string.charAt(0);
            switch (dauLoto) {
                case '0':
                    gt.lstDau0.add(string);
                    break;
                case '1':
                    gt.lstDau1.add(string);
                    break;
                case '2':
                    gt.lstDau2.add(string);
                    break;
                case '3':
                    gt.lstDau3.add(string);
                    break;
                case '4':
                    gt.lstDau4.add(string);
                    break;
                case '5':
                    gt.lstDau5.add(string);
                    break;
                case '6':
                    gt.lstDau6.add(string);
                    break;
                case '7':
                    gt.lstDau7.add(string);
                    break;
                case '8':
                    gt.lstDau8.add(string);
                    break;
                case '9':
                    gt.lstDau9.add(string);
                    break;
            }
        }
        //Hiển thị Đầu Loto lên bảng
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (gt.lstDau0.size() > 0) {
            String strDau0 = "";
            for (String string : gt.lstDau0) {
                strDau0 = strDau0 + ";" + string;
            }
            model.setValueAt(strDau0.substring(1, strDau0.length()), 0, 1);
        } else {
            model.setValueAt(" ", 0, 1);
        }
        if (gt.lstDau1.size() > 0) {
            String strDau1 = "";
            for (String string : gt.lstDau1) {
                strDau1 = strDau1 + ";" + string;
            }
            model.setValueAt(strDau1.substring(1, strDau1.length()), 1, 1);
        } else {
            model.setValueAt(" ", 1, 1);
        }

        if (gt.lstDau2.size() > 0) {
            String strDau2 = "";
            for (String string : gt.lstDau2) {
                strDau2 = strDau2 + ";" + string;
            }
            model.setValueAt(strDau2.substring(1, strDau2.length()), 2, 1);
        } else {
            model.setValueAt(" ", 2, 1);
        }
        if (gt.lstDau3.size() > 0) {
            String strDau3 = "";
            for (String string : gt.lstDau3) {
                strDau3 = strDau3 + ";" + string;
            }
            model.setValueAt(strDau3.substring(1, strDau3.length()), 3, 1);
        } else {
            model.setValueAt(" ", 3, 1);
        }
        if (gt.lstDau4.size() > 0) {
            String strDau4 = "";
            for (String string : gt.lstDau4) {
                strDau4 = strDau4 + ";" + string;
            }
            model.setValueAt(strDau4.substring(1, strDau4.length()), 4, 1);
        } else {
            model.setValueAt(" ", 4, 1);
        }

        if (gt.lstDau5.size() > 0) {
            String strDau5 = "";
            for (String string : gt.lstDau5) {
                strDau5 = strDau5 + ";" + string;
            }
            model.setValueAt(strDau5.substring(1, strDau5.length()), 5, 1);
        } else {
            model.setValueAt(" ", 5, 1);
        }
        if (gt.lstDau6.size() > 0) {
            String strDau6 = "";
            for (String string : gt.lstDau6) {
                strDau6 = strDau6 + ";" + string;
            }

            model.setValueAt(strDau6.substring(1, strDau6.length()), 6, 1);
        } else {
            model.setValueAt(" ", 6, 1);
        }
        if (gt.lstDau7.size() > 0) {
            String strDau7 = "";
            for (String string : gt.lstDau7) {
                strDau7 = strDau7 + ";" + string;
            }
            model.setValueAt(strDau7.substring(1, strDau7.length()), 7, 1);
        } else {
            model.setValueAt(" ", 7, 1);
        }
        if (gt.lstDau8.size() > 0) {
            String strDau8 = "";
            for (String string : gt.lstDau8) {
                strDau8 = strDau8 + ";" + string;
            }
            model.setValueAt(strDau8.substring(1, strDau8.length()), 8, 1);
        } else {
            model.setValueAt(" ", 8, 1);
        }
        if (gt.lstDau9.size() > 0) {

            String strDau9 = "";
            for (String string : gt.lstDau9) {
                strDau9 = strDau9 + ";" + string;
            }
            model.setValueAt(strDau9.substring(1, strDau9.length()), 9, 1);
        } else {
            model.setValueAt(" ", 9, 1);
        }

        // Kiem tra trung DE
        if (strDe.equals(gt.strDB.substring(3))) {
            
            JOptionPane.showMessageDialog(rootPane, "Đề về " + strDe + "!\nBạn nhận được " + iTienDe * 70 + " VND tiền thưởng!");
            tongTienThuong += iTienDe*70;
        }
        // check trung LO 
        int count = 0;
        for (String string : gt.lstLo) {
            if (strLo.equals(string)) {
                count++;
            }

        }
        if (count > 0) {
            gt.tienThuong = (iTienLo / 23) * 80 * count;
            JOptionPane.showMessageDialog(rootPane, "Bạn đã trúng Lô " + count + " nháy!\n" + "Tổng tiền nhận thêm: " + gt.tienThuong + " VND");
            tongTienThuong = tongTienThuong+ gt.tienThuong;
        }
        
        txtTongTien.setText(""+tongTienThuong);
        DateFormat datef = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        txtDay.setText(datef.format(cal.getTime()));

        arrGiaiThuong.put(datef.format(cal.getTime()), gt);
        System.out.println(datef.format(cal.getTime()));


    }//GEN-LAST:event_btnRollActionPerformed
    public static Map<String, GiaiThuong> arrGiaiThuong = new HashMap();
    private void txtNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNam1ActionPerformed

    private void btnViewDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDateActionPerformed
        // TODO add your handling code here:
        String strGetDate = "";
        strGetDate = txtGetDate.getText();
        if (strGetDate.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập gì cả!");
            return;
        }

        GiaiThuong showGt = arrGiaiThuong.get(strGetDate);

        System.out.println(showGt.strDB);

        txtDB.setText(showGt.strDB);
        txtNhat.setText(showGt.strNhat);
        txtNhi1.setText(showGt.strNhi1);
        txtNhi2.setText(showGt.strNhi2);
        txtBa1.setText(showGt.strBa[0]);
        txtBa2.setText(showGt.strBa[1]);
        txtBa3.setText(showGt.strBa[2]);
        txtBa4.setText(showGt.strBa[3]);
        txtBa5.setText(showGt.strBa[4]);
        txtBa6.setText(showGt.strBa[5]);
        txtTu1.setText(showGt.strTu[0]);
        txtTu2.setText(showGt.strTu[1]);
        txtTu3.setText(showGt.strTu[2]);
        txtTu4.setText(showGt.strTu[3]);
        txtNam1.setText(showGt.strNam[0]);
        txtNam2.setText(showGt.strNam[1]);
        txtNam3.setText(showGt.strNam[2]);
        txtNam4.setText(showGt.strNam[3]);
        txtNam5.setText(showGt.strNam[4]);
        txtNam6.setText(showGt.strNam[5]);
        txtSau1.setText(showGt.strSau[0]);
        txtSau2.setText(showGt.strSau[1]);
        txtSau3.setText(showGt.strSau[2]);
        txtBay1.setText(showGt.strBay[0]);
        txtBay2.setText(showGt.strBay[1]);
        txtBay3.setText(showGt.strBay[2]);
        txtBay4.setText(showGt.strBay[3]);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (showGt.lstDau0.size() > 0) {
            String strDau0 = "";
            for (String string : showGt.lstDau0) {
                strDau0 = strDau0 + ";" + string;
            }
            model.setValueAt(strDau0.substring(1, strDau0.length()), 0, 1);
        } else {
            model.setValueAt(" ", 0, 1);
        }
        if (showGt.lstDau1.size() > 0) {
            String strDau1 = "";
            for (String string : showGt.lstDau1) {
                strDau1 = strDau1 + ";" + string;
            }
            model.setValueAt(strDau1.substring(1, strDau1.length()), 1, 1);
        } else {
            model.setValueAt(" ", 1, 1);
        }

        if (showGt.lstDau2.size() > 0) {
            String strDau2 = "";
            for (String string : showGt.lstDau2) {
                strDau2 = strDau2 + ";" + string;
            }
            model.setValueAt(strDau2.substring(1, strDau2.length()), 2, 1);
        } else {
            model.setValueAt(" ", 2, 1);
        }
        if (showGt.lstDau3.size() > 0) {
            String strDau3 = "";
            for (String string : showGt.lstDau3) {
                strDau3 = strDau3 + ";" + string;
            }
            model.setValueAt(strDau3.substring(1, strDau3.length()), 3, 1);
        } else {
            model.setValueAt(" ", 3, 1);
        }
        if (showGt.lstDau4.size() > 0) {
            String strDau4 = "";
            for (String string : showGt.lstDau4) {
                strDau4 = strDau4 + ";" + string;
            }
            model.setValueAt(strDau4.substring(1, strDau4.length()), 4, 1);
        } else {
            model.setValueAt(" ", 4, 1);
        }

        if (showGt.lstDau5.size() > 0) {
            String strDau5 = "";
            for (String string : showGt.lstDau5) {
                strDau5 = strDau5 + ";" + string;
            }
            model.setValueAt(strDau5.substring(1, strDau5.length()), 5, 1);
        } else {
            model.setValueAt(" ", 5, 1);
        }
        if (showGt.lstDau6.size() > 0) {
            String strDau6 = "";
            for (String string : showGt.lstDau6) {
                strDau6 = strDau6 + ";" + string;
            }

            model.setValueAt(strDau6.substring(1, strDau6.length()), 6, 1);
        } else {
            model.setValueAt(" ", 6, 1);
        }
        if (showGt.lstDau7.size() > 0) {
            String strDau7 = "";
            for (String string : showGt.lstDau7) {
                strDau7 = strDau7 + ";" + string;
            }
            model.setValueAt(strDau7.substring(1, strDau7.length()), 7, 1);
        } else {
            model.setValueAt(" ", 7, 1);
        }
        if (showGt.lstDau8.size() > 0) {
            String strDau8 = "";
            for (String string : showGt.lstDau8) {
                strDau8 = strDau8 + ";" + string;
            }
            model.setValueAt(strDau8.substring(1, strDau8.length()), 8, 1);
        } else {
            model.setValueAt(" ", 8, 1);
        }
        if (showGt.lstDau9.size() > 0) {

            String strDau9 = "";
            for (String string : showGt.lstDau9) {
                strDau9 = strDau9 + ";" + string;
            }
            model.setValueAt(strDau9.substring(1, strDau9.length()), 9, 1);
        } else {
            model.setValueAt(" ", 9, 1);
        }
    }//GEN-LAST:event_btnViewDateActionPerformed
    public static int tongTienThuong;
    public class GiaiThuong {
        int tienThuong = 0;

        String strDB, strNhat, strNhi1, strNhi2;
        String[] strBa = new String[6];
        String[] strTu = new String[4];
        String[] strNam = new String[6];
        String[] strSau = new String[3];
        String[] strBay = new String[4];
        List<String> lstLo = new ArrayList();
        List<String> lstDau0 = new ArrayList();
        List<String> lstDau1 = new ArrayList();
        List<String> lstDau2 = new ArrayList();
        List<String> lstDau3 = new ArrayList();
        List<String> lstDau4 = new ArrayList();
        List<String> lstDau5 = new ArrayList();
        List<String> lstDau6 = new ArrayList();
        List<String> lstDau7 = new ArrayList();
        List<String> lstDau8 = new ArrayList();
        List<String> lstDau9 = new ArrayList();

        public GiaiThuong() {
        }
    }

    public static String check(String aStr, int numberType) {
        int length = aStr.length();
        String str = "00000";
        str = str.substring((5 - numberType));

        for (int i = 0; i <= 5; i++) {
            if (length == i) {
                str = str.substring(i);
                break;
            }
        }
        return str + aStr;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TroiChoiXoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TroiChoiXoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TroiChoiXoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TroiChoiXoSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TroiChoiXoSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoll;
    private javax.swing.JButton btnViewDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBa1;
    private javax.swing.JTextField txtBa2;
    private javax.swing.JTextField txtBa3;
    private javax.swing.JTextField txtBa4;
    private javax.swing.JTextField txtBa5;
    private javax.swing.JTextField txtBa6;
    private javax.swing.JTextField txtBay1;
    private javax.swing.JTextField txtBay2;
    private javax.swing.JTextField txtBay3;
    private javax.swing.JTextField txtBay4;
    private javax.swing.JTextField txtDB;
    private javax.swing.JLabel txtDay;
    private javax.swing.JTextField txtGetDate;
    private javax.swing.JTextField txtNam1;
    private javax.swing.JTextField txtNam2;
    private javax.swing.JTextField txtNam3;
    private javax.swing.JTextField txtNam4;
    private javax.swing.JTextField txtNam5;
    private javax.swing.JTextField txtNam6;
    private javax.swing.JTextField txtNhat;
    private javax.swing.JTextField txtNhi1;
    private javax.swing.JTextField txtNhi2;
    private javax.swing.JTextField txtSau1;
    private javax.swing.JTextField txtSau2;
    private javax.swing.JTextField txtSau3;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtTu1;
    private javax.swing.JTextField txtTu2;
    private javax.swing.JTextField txtTu3;
    private javax.swing.JTextField txtTu4;
    private javax.swing.JTextField txtgetDe;
    private javax.swing.JTextField txtgetDiemLo;
    private javax.swing.JTextField txtgetLo;
    private javax.swing.JTextField txtgetTienDe;
    // End of variables declaration//GEN-END:variables
}
